# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-12 10:50
from __future__ import unicode_literals

from django.db import migrations

def add_init_data(apps, schema_editor):
    IssueField = apps.get_model('issues', 'IssueField')

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_init_issuestatusfield'),
    ]

    operations = [
    ]
